import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Footer, FooterBanner, HeroBanner, Product } from '../components'
import { client } from '../lib/client'
import { Banner, type Product as ProductType } from '../@types/types'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ products, banner }: { products: ProductType[], banner: Banner}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroBanner banner={banner} />
        <div className='products-heading'>
          <h2>Best Selling Products</h2>
          <p>Speakers of many variations</p>
        </div>

        <div className='products-container'>
          {products?.map((product) => (
            <Product key={product._id} product={product} />
          ))}
        </div>
        <FooterBanner banner={banner} />
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  // const products = await client.fetch(
  //   `*[_type == "product"]{
  //     _id,
  //     name,
  //     slug,
  //     price,
  //     image,
  //     description,
  //   }`
  // )

  const products = await client.fetch(
    `*[_type == "product"]`
  )

  const banner = await client.fetch(
    `*[_type == "banner"]`
  )

  // console.dir({ products, banner }, { depth: null })
  return {
    props: {
      products,
      banner: banner[0],
    },
  }
}
